version: '3.7'

services: 
  infrastructure:
    build: ./infrastructure
    expose:  
      - '8080'
    restart: on-failure:3

  server:
    build: ./server
    ports:
      - 0.0.0.0:5000:5000
    depends_on: 
      - infrastructure

    restart: on-failure:3
    links:
      - infrastructure